### ISSUE TITLE
Latin letter "q" is not transliterated to Russian

### ISSUE THREAD

**Issue by rominf** [opendatakosovo/cyrillic-transliteration#27]
When I try to transliterate any word written in Latin, which contain letter `q`, `q` letter kept as is. 

Example:
```
In [1]: import cyrtranslit

In [2]: cyrtranslit.to_cyrillic('Question', lang_code='ru')
Out[2]: 'Qуестион'
```

Letter `q` doesn't exist in Russian alphabet, and in most cases `q` should be replaced with `к`.

**Comment by rominf** [comment]
OK, I've found https://github.com/opendatakosovo/cyrillic-transliteration/pull/11 and it fixed the situation. I'll take a look if I can fix the tests.

**Comment by georgeslabreche** [comment]
Issue fixed with https://github.com/opendatakosovo/cyrillic-transliteration/pull/28
