### ISSUE TITLE
Why not combine all *_CYR_TO_LAT_DICTs?

### ISSUE THREAD

**Issue by bittlingmayer** [opendatakosovo/cyrillic-transliteration#3]
It seems to me that the safest code would simply combine all 3 - sr, me and mk.

The extra letters in me and mk do not conflict with any sr letters.

That way, a client can pass any Western South Slavic Cyrillic text, and be guaranteed an output.

(Likewise, in production code I would want Russian or Bulgarian letters to be handled in some way, in case they occur in text my code must process.)

**Comment by georgeslabreche** [comment]
True. I put the separation of concern/languages as a simple way to be straightforward and clear for someone who would want to include new languages. Maybe this should be fixed to allow both options?

**Comment by bittlingmayer** [comment]
I see your point.  eg 'Ева-Камилица Халидова Петрушка' -> 'Eva-Kamilica Halidova Petruška' if Western South Slavic, but 'Yeva-Kamilitsa Khalidova Petrushka' if Russian...

It's just that `me` is not really standard ISO.  When interacting with other systems, like NLTK, Google Translate language detection API etc, anything with `з́` will at best be classified as `sr`.
