### ISSUE TITLE
Reference of mappings

### ISSUE THREAD

**Issue by sublee** [opendatakosovo/cyrillic-transliteration#36]
Thank to develop and share this great project. I wonder what is the reference or historical background of the Cyrillic-Latin mappings in CyrTranslit. Is it based on the [Soviet project](https://en.wikipedia.org/wiki/Russian_Latin_alphabet#Soviet_project)? Or something similar exsiting transliteration scheme?

**Comment by georgeslabreche** [comment]
Hi! Thank you for your interest! We simply trusted individual contributors to come up with mappings based on their own knowledge and researcher. Refer to the "[How can I contribute?](https://github.com/opendatakosovo/cyrillic-transliteration#how-can-i-contribute)" section of the README to see a list of who contributed.

**Comment by sublee** [comment]
Thank you for the answer. :)
