### ISSUE TITLE
ImportError: No module named 'mapping'

### ISSUE THREAD

**Issue by sorrat** [opendatakosovo/cyrillic-transliteration#6]
python 3.5.2
cyrtranslit-0.3

Traceback:
```
>>> import cyrtranslit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.5/site-packages/cyrtranslit/__init__.py", line 2, in <module>
    from mapping import TRANSLIT_DICT
ImportError: No module named 'mapping'
```

**Comment by rspeer** [comment]
I have the same problem. Looks like it's meant to import the local module `.mapping`.

**Comment by georgeslabreche** [comment]
Yes, it's meant to import TRANSLIT_DICT from [mapping.py](https://github.com/opendatakosovo/cyrillic-transliteration/blob/master/cyrtranslit/mapping.py)

How did you install it? I just opened Terminal and did the following:

```
python -m pip install cyrtranslit 
python
>>> import cyrtranslit
>>> cyrtranslit.supported()
['me', 'sr', 'mk', 'ru']
```

However, I am using Python 2.7.10 whereas @sorrat is using 3.5.2. Which version are you using @rspeer ?

**Comment by sorrat** [comment]
The library does not support python3:

* no relative imports
* `iteritems`

**Comment by rspeer** [comment]
Also using 3.5.2, and yes, the problems are what sorrat described.

I assumed that Python 3 would be fine because there are versions of Python 3 listed in the setup.py.

**Comment by georgeslabreche** [comment]
@sorrat @rspeer here's an abstract of the issue:
http://legacy.python.org/dev/peps/pep-0469/#abstract

To fix this, we need to update [mapping.py](https://github.com/opendatakosovo/cyrillic-transliteration/blob/v0.3/cyrtranslit/mapping.py) and replace every instance of d.iteritems() with iter(d.items()):

- [SR_CYR_TO_LAT_DICT.iteritems() --> iter(SR_CYR_TO_LAT_DICT.items())](https://github.com/opendatakosovo/cyrillic-transliteration/blob/v0.3/cyrtranslit/mapping.py#L41)
- [ME_CYR_TO_LAT_DICT.iteritems() --> iter(ME_CYR_TO_LAT_DICT.items())](https://github.com/opendatakosovo/cyrillic-transliteration/blob/master/cyrtranslit/mapping.py#L57)
- [MK_CYR_TO_LAT_DICT.iteritems() --> iter(MK_CYR_TO_LAT_DICT.items())](https://github.com/opendatakosovo/cyrillic-transliteration/blob/master/cyrtranslit/mapping.py#L84)
- [RU_CYR_TO_LAT_DICT.iteritems() --> iter(RU_CYR_TO_LAT_DICT.items())](https://github.com/opendatakosovo/cyrillic-transliteration/blob/v0.3/cyrtranslit/mapping.py#L124)

Furthermore, list comprehension is not supported in Python 2.6 so I will remove that version from the supported Python version list in setup.py.

Here's the [pull request](https://github.com/opendatakosovo/cyrillic-transliteration/pull/7/commits/e98be9bc6497f661d3553295db34d2f8d1772927) for the fix currently on the [python3-iteritems-fix](https://github.com/opendatakosovo/cyrillic-transliteration/tree/python3-iteritems-fix) branch.

If someone can confirm that it now works with their Python 3 environment then I will happily merge the pull request to master and release this new version to PyPI.

**Comment by georgeslabreche** [comment]
Still need to resolve issue #8 raised by @savagej.

**Comment by georgeslabreche** [comment]
@sorrat @rspeer, the master branch is now the candidate release for version 0.4 to PyPI. Let me know if it looks good on your end.

**Comment by sorrat** [comment]
@georgeslabreche no issues found.

**Comment by georgeslabreche** [comment]
@sorrat @rspeer: CyrTranslit v0.4 has been uploaded to PyPI: https://pypi.python.org/pypi/cyrtranslit
Thank you all for your help.
