### ISSUE TITLE
Python 3: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by savagej** [opendatakosovo/cyrillic-transliteration#8]
`string_to_transliterate = string_to_transliterate.decode('utf-8')` does not work in Python 3, returns the error
> AttributeError: 'str' object has no attribute 'decode'

Similarly, `return latinized_str.encode('utf-8')` means a byte-string is returned in Python 3.
> b'my latin string'

Removing the encode and decode of strings in __init__.py makes the package work with python 3

Related to issue #6

**Comment by georgeslabreche** [comment]
I would have to preserve backward compatibility, though. Is there a cleaner way than the following approach?

```
if sys.version_info < (3, 0):
    return cyrillic_str.encode('utf-8')
else:
    return cyrillic_str 
```

**Comment by savagej** [comment]
[Looks like the other major package uses six](https://github.com/barseghyanartur/transliterate/search?utf8=%E2%9C%93&q=six&type=Code) for backwards compatibility management. I'd guess that using six would be overkill for this though, probably what you suggested would be perfect.

**Comment by georgeslabreche** [comment]
@savagej thank you for your contribution! Master branch is now the candidate release for version 0.4 to PyPI. Let me know if it looks good on your end.

**Comment by georgeslabreche** [comment]
@savagej: CyrTranslit v0.4 has been uploaded to PyPI: https://pypi.python.org/pypi/cyrtranslit
Thank you for your help.
